language: python
python:
- 3.6
- 3.5
- 3.4
script: python setup.py test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: milesg
  password:
    secure: hgyHMIWZebYda6k8JtQN4jePLE7Qt9kdJ2S8rFzQJP8QIGD+ysmFOonG15YbDzH/HbrmTrfTkkzYe8jqPtAr7GQvsGi6l+2dvE4zkzJCjGvDl9mt5IjPRKMSri8KClCVoFNgwFxOt+10Z08fF5/INPOuxD2pN2Zx2hXw2Vpx4xdhACIQaEu0x8sXEQTMUO1fBrKLOT3OsewJmFH07xJ+Ot+Xf3xZxxWw5C5NaSgjbi1+oJ+JyKX3KJ1SjByrUdJSM01qPTE1jhP8rm3Lw01tHxS58V+CeRUS3miFcl2HbvYCF2eOEjeAkK0Rb8XkHvB9T6IihqlcpMTlUVVvOTLuEV/dp0gBilIw25JsqPGIpXGV+ifDpUWDg8cG1JQ9s61+5dNTTjOmze7Azc6R6lPdKop+GBfk8YbKAPqDt151Nj5J13DYJWU475w/2IhJY0NszA/OJK94b7l4bAU70VUDQkCLDRQa65+U5HqfsCar2neVlR4IbU/j75Qe0b7GFBwP5cmmMsJaUeE7RPGBudQJSvTLBE4p4hZKR0ZGQZieGB2IFS0ooHIn0x+fo46ON2sFjidpoIKLEHUOXAjqeTF5/q2+M1Nvpzps7agThTM74Yg2XDH8a16iTXMfNipLvtapTuB2xavYx1bRmjurzrOvedko4mPGkhr0f4mpE6V/qEg=
  on:
    tags: true
    repo: milesgranger/altitudo
    python: 3.6
